# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computes distances between pairs of observations using iRF-encoded binary
#' features.
#'
#' @param obsn node membership matrix indicating which leaf node observations
#'   fall in for each tree, rows being observations, cols being trees.
#' @param featn binary matrix indicating iRF decision path encodings, rows
#'   being nodes, cols being features.
#' @param idtree vector indicating rows of featn that correspond to new trees.
#' @param ridx first index of a pair for which to compute distance.
#' @param cidx second index of a pair for which to compute distance.
#' @return Product of v1 and v2
forestDist <- function(obsn, featn, idtree, ridx, cidx) {
    .Call(`_rfdistance_forestDist`, obsn, featn, idtree, ridx, cidx)
}

treeDist <- function(x, nk) {
    .Call(`_rfdistance_treeDist`, x, nk)
}

